[package]
name = "sterling_number"
version = "0.1.0"
authors = ["fajara"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigdecimal = "0.1.2"